<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ3x2qyu\App_KernelProDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ3x2qyu/App_KernelProDebugContainer.php') {
    touch(__DIR__.'/ContainerZ3x2qyu.legacy');

    return;
}

if (!\class_exists(App_KernelProDebugContainer::class, false)) {
    \class_alias(\ContainerZ3x2qyu\App_KernelProDebugContainer::class, App_KernelProDebugContainer::class, false);
}

return new \ContainerZ3x2qyu\App_KernelProDebugContainer([
    'container.build_hash' => 'Z3x2qyu',
    'container.build_id' => 'e80168e3',
    'container.build_time' => 1764724052,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ3x2qyu');
