<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_club' => [[], ['_controller' => 'App\\Controller\\ClubController::index'], [], [['text', '/club']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/register']], [], [], []],
    'app_sportif' => [[], ['_controller' => 'App\\Controller\\SportifController::index'], [], [['text', '/sportif']], [], [], []],
    'App\Controller\ClubController::index' => [[], ['_controller' => 'App\\Controller\\ClubController::index'], [], [['text', '/club']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\LoginController::index' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'App\Controller\RegisterController::index' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/register']], [], [], []],
    'App\Controller\SportifController::index' => [[], ['_controller' => 'App\\Controller\\SportifController::index'], [], [['text', '/sportif']], [], [], []],
];
