<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sportif extends \App\Entity\Sportif implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'age' => [parent::class, 'age', null, 16],
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'categorie_age' => [parent::class, 'categorie_age', null, 16],
        "\0".parent::class."\0".'club' => [parent::class, 'club', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'infos' => [parent::class, 'infos', null, 16],
        "\0".parent::class."\0".'naissance' => [parent::class, 'naissance', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null, 16],
        "\0".parent::class."\0".'poste' => [parent::class, 'poste', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'taille' => [parent::class, 'taille', null, 16],
        'age' => [parent::class, 'age', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'categorie_age' => [parent::class, 'categorie_age', null, 16],
        'club' => [parent::class, 'club', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'infos' => [parent::class, 'infos', null, 16],
        'naissance' => [parent::class, 'naissance', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'photo' => [parent::class, 'photo', null, 16],
        'poste' => [parent::class, 'poste', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'taille' => [parent::class, 'taille', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
