<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Club extends \App\Entity\Club implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Categorie' => [parent::class, 'Categorie', null, 16],
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'championnat' => [parent::class, 'championnat', null, 16],
        "\0".parent::class."\0".'couleurs' => [parent::class, 'couleurs', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'entraineur' => [parent::class, 'entraineur', null, 16],
        "\0".parent::class."\0".'fondation' => [parent::class, 'fondation', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'infos' => [parent::class, 'infos', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'president' => [parent::class, 'president', null, 16],
        "\0".parent::class."\0".'proprietaire' => [parent::class, 'proprietaire', null, 16],
        "\0".parent::class."\0".'sportifs' => [parent::class, 'sportifs', null, 16],
        "\0".parent::class."\0".'stade' => [parent::class, 'stade', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'website' => [parent::class, 'website', null, 16],
        'Categorie' => [parent::class, 'Categorie', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'championnat' => [parent::class, 'championnat', null, 16],
        'couleurs' => [parent::class, 'couleurs', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'entraineur' => [parent::class, 'entraineur', null, 16],
        'fondation' => [parent::class, 'fondation', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'infos' => [parent::class, 'infos', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'president' => [parent::class, 'president', null, 16],
        'proprietaire' => [parent::class, 'proprietaire', null, 16],
        'sportifs' => [parent::class, 'sportifs', null, 16],
        'stade' => [parent::class, 'stade', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'website' => [parent::class, 'website', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
