<?php

namespace ContainerA3xXM6R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UZsk2PWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uZsk2PW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uZsk2PW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminRegisterController::index' => ['privates', '.service_locator.A84gqGd.App\\Controller\\AdminRegisterController::index()', 'getAdminRegisterControllerindexService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\admin\\AdminController::index' => ['privates', '.service_locator.H.OnvBw.App\\Controller\\admin\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\admin\\AdminController::profil_admin' => ['privates', '.service_locator.H.OnvBw.App\\Controller\\admin\\AdminController::profil_admin()', 'getAdminControllerprofilAdminService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminRegisterController:index' => ['privates', '.service_locator.A84gqGd.App\\Controller\\AdminRegisterController::index()', 'getAdminRegisterControllerindexService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\admin\\AdminController:index' => ['privates', '.service_locator.H.OnvBw.App\\Controller\\admin\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\admin\\AdminController:profil_admin' => ['privates', '.service_locator.H.OnvBw.App\\Controller\\admin\\AdminController::profil_admin()', 'getAdminControllerprofilAdminService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminRegisterController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\admin\\AdminController::index' => '?',
            'App\\Controller\\admin\\AdminController::profil_admin' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminRegisterController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\admin\\AdminController:index' => '?',
            'App\\Controller\\admin\\AdminController:profil_admin' => '?',
        ]);
    }
}
