<?php

namespace ContainerQQa2t39;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H.OnvBw.App\Controller\admin\AdminController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H.OnvBw.App\\Controller\\admin\\AdminController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'UserRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'UserRepo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\admin\\AdminController::index()', $container);
    }
}
