<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYC0uHZx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYC0uHZx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYC0uHZx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYC0uHZx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYC0uHZx\App_KernelDevDebugContainer([
    'container.build_hash' => 'YC0uHZx',
    'container.build_id' => '4ec87b18',
    'container.build_time' => 1765148062,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYC0uHZx');
